### ISSUE TITLE
[BUG] Notebook broken: getting error from `ensemble.export(export_path)` step in multi-stage serving example nb

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/systems#286]
### Bug description

When I run [this notebook ](https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb), I get the following error from the  `ens_config, node_configs = ensemble.export(export_path)` step:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[24], line 1
----> 1 ens_config, node_configs = ensemble.export(export_path)

File /usr/local/lib/python3.8/dist-packages/merlin/systems/dag/ensemble.py:153, in Ensemble.export(self, export_path, runtime, **kwargs)
    148 """
    149 Write out an ensemble model configuration directory. The exported
    150 ensemble is designed for use with Triton Inference Server.
    151 """
    152 runtime = runtime or TritonExecutorRuntime()
--> 153 return runtime.export(self, export_path, **kwargs)

File /usr/local/lib/python3.8/dist-packages/merlin/systems/dag/runtimes/triton/runtime.py:147, in TritonExecutorRuntime.export(self, ensemble, path, version, name)
    144         if node_config is not None:
    145             node_configs.append(node_config)
--> 147 executor_config = self._executor_model_export(path, name, ensemble)
    149 return (executor_config, node_configs)

File /usr/local/lib/python3.8/dist-packages/merlin/systems/dag/runtimes/triton/runtime.py:218, in TritonExecutorRuntime._executor_model_export(self, path, export_name, ensemble, params, node_id, version)
    210 with importlib.resources.path(
    211     "merlin.systems.triton.models", "executor_model.py"
    212 ) as executor_model:
    213     copyfile(
    214         executor_model,
    215         os.path.join(node_export_path, str(version), "model.py"),
    216     )
--> 218 ensemble.save(os.path.join(node_export_path, str(version), "ensemble"))
    220 return config

File /usr/local/lib/python3.8/dist-packages/merlin/systems/dag/ensemble.py:107, in Ensemble.save(self, path)
    105 # dump out the full workflow (graph/stats/operators etc) using cloudpickle
    106 with fs.open(fs.sep.join([path, "ensemble.pkl"]), "wb") as o:
--> 107     cloudpickle.dump(self, o)

File /usr/local/lib/python3.8/dist-packages/cloudpickle/cloudpickle_fast.py:55, in dump(obj, file, protocol, buffer_callback)
     45 def dump(obj, file, protocol=None, buffer_callback=None):
     46     """Serialize obj as bytes streamed into file
     47 
     48     protocol defaults to cloudpickle.DEFAULT_PROTOCOL which is an alias to
   (...)
     53     compatibility with older versions of Python.
     54     """
---> 55     CloudPickler(
     56         file, protocol=protocol, buffer_callback=buffer_callback
     57     ).dump(obj)

File /usr/local/lib/python3.8/dist-packages/cloudpickle/cloudpickle_fast.py:632, in CloudPickler.dump(self, obj)
    630 def dump(self, obj):
    631     try:
--> 632         return Pickler.dump(self, obj)
    633     except RuntimeError as e:
    634         if "recursion" in e.args[0]:

File /usr/local/lib/python3.8/dist-packages/keras/engine/training.py:363, in Model.__reduce__(self)
    359 def __reduce__(self):
    360     if self.built:
    361         return (
    362             pickle_utils.deserialize_model_from_bytecode,
--> 363             pickle_utils.serialize_model_as_bytecode(self),
    364         )
    365     else:
    366         # SavedModel (and hence serialize_model_as_bytecode) only support
    367         # built models, but if the model is not built,
   (...)
    371         # the superclass hierarchy to get an implementation of __reduce__
    372         # that can pickle this Model as a plain Python object.
    373         return super().__reduce__()

File /usr/local/lib/python3.8/dist-packages/keras/saving/pickle_utils.py:63, in serialize_model_as_bytecode(model)
     53 """Convert a Keras Model into a bytecode representation for pickling.
     54 
     55 Args:
   (...)
     60         `deserialize_from_bytecode`.
     61 """
     62 temp_dir = f"[ram://{uuid.](ram://{uuid.uuid4)[uuid4](ram://{uuid.uuid4)()}"
---> 63 model.save(temp_dir)
     64 b = io.BytesIO()
     65 with tarfile.open(fileobj=b, mode="w") as archive:

File /usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_filev23458px.py:14, in outer_factory.<locals>.inner_factory.<locals>.tf___wrapped_model(*args, **kwargs)
     12 (args, kwargs) = ag__.converted_call(ag__.ld(model)._call_spec.set_arg_value, ('training', False, ag__.ld(args), ag__.ld(kwargs)), dict(inputs_in_args=True), fscope)
     13 with ag__.ld(base_layer_utils).call_context().enter(ag__.ld(model), inputs=None, build_graph=False, training=False, saving=True):
---> 14     outputs = ag__.converted_call(ag__.ld(model), tuple(ag__.ld(args)), dict(**ag__.ld(kwargs)), fscope)
     15 output_names = ag__.ld(model).output_names
     17 def get_state():

ValueError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 147, in _wrapped_model  *
        outputs = model(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "model" "                 f"(type merlin.models>Model).
    
    Could not find matching concrete function to call loaded from the SavedModel. Got:
      Positional arguments (5 total):
        * {'item_brand': <tf.Tensor 'inputs:0' shape=(None, 1) dtype=int32>,
     'item_category': <tf.Tensor 'inputs_1:0' shape=(None, 1) dtype=int32>,
     'item_id': <tf.Tensor 'inputs_2:0' shape=(None, 1) dtype=int32>,
     'item_id_raw': <tf.Tensor 'inputs_3:0' shape=(None, 1) dtype=int32>,
     'item_shop': <tf.Tensor 'inputs_4:0' shape=(None, 1) dtype=int32>,
     'user_age': <tf.Tensor 'inputs_5:0' shape=(None, 1) dtype=int32>,
     'user_brands': <tf.Tensor 'inputs_6:0' shape=(None, 1) dtype=int32>,
     'user_categories': <tf.Tensor 'inputs_7:0' shape=(None, 1) dtype=int32>,
     'user_consumption_2': <tf.Tensor 'inputs_8:0' shape=(None, 1) dtype=int32>,
     'user_gender': <tf.Tensor 'inputs_9:0' shape=(None, 1) dtype=int32>,
     'user_geography': <tf.Tensor 'inputs_10:0' shape=(None, 1) dtype=int32>,
     'user_group': <tf.Tensor 'inputs_11:0' shape=(None, 1) dtype=int32>,
     'user_id': <tf.Tensor 'inputs_12:0' shape=(None, 1) dtype=int32>,
     'user_id_raw': <tf.Tensor 'inputs_13:0' shape=(None, 1) dtype=int32>,
     'user_intentions': <tf.Tensor 'inputs_14:0' shape=(None, 1) dtype=int32>,
     'user_is_occupied': <tf.Tensor 'inputs_15:0' shape=(None, 1) dtype=int32>,
     'user_profile': <tf.Tensor 'inputs_16:0' shape=(None, 1) dtype=int32>,
     'user_shops': <tf.Tensor 'inputs_17:0' shape=(None, 1) dtype=int32>}
        * None
        * False
        * None
        * None
      Keyword arguments: {}
    
     Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (5 total):
        * {'item_brand': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_brand'),
     'item_category': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_category'),
     'item_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_id'),
     'item_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_id_raw'),
     'item_shop': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_shop'),
     'user_age': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_age'),
     'user_brands': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_brands'),
     'user_categories': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_categories'),
     'user_consumption_2': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_consumption_2'),
     'user_gender': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_gender'),
     'user_geography': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_geography'),
     'user_group': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_group'),
     'user_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_id'),
     'user_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_id_raw'),
     'user_intentions': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_intentions'),
     'user_is_occupied': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_is_occupied'),
     'user_profile': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_profile'),
     'user_shops': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_shops')}
        * None
        * False
        * False
        * False
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (5 total):
        * {'item_brand': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_brand'),
     'item_category': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_category'),
     'item_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_id'),
     'item_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_id_raw'),
     'item_shop': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/item_shop'),
     'user_age': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_age'),
     'user_brands': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_brands'),
     'user_categories': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_categories'),
     'user_consumption_2': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_consumption_2'),
     'user_gender': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_gender'),
     'user_geography': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_geography'),
     'user_group': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_group'),
     'user_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_id'),
     'user_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_id_raw'),
     'user_intentions': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_intentions'),
     'user_is_occupied': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_is_occupied'),
     'user_profile': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_profile'),
     'user_shops': TensorSpec(shape=(None, 1), dtype=tf.int32, name='inputs/user_shops')}
        * None
        * True
        * False
        * False
      Keyword arguments: {}
    
    Option 3:
      Positional arguments (5 total):
        * {'item_brand': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_brand'),
     'item_category': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_category'),
     'item_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_id'),
     'item_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_id_raw'),
     'item_shop': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_shop'),
     'user_age': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_age'),
     'user_brands': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_brands'),
     'user_categories': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_categories'),
     'user_consumption_2': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_consumption_2'),
     'user_gender': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_gender'),
     'user_geography': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_geography'),
     'user_group': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_group'),
     'user_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_id'),
     'user_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_id_raw'),
     'user_intentions': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_intentions'),
     'user_is_occupied': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_is_occupied'),
     'user_profile': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_profile'),
     'user_shops': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_shops')}
        * None
        * False
        * False
        * False
      Keyword arguments: {}
    
    Option 4:
      Positional arguments (5 total):
        * {'item_brand': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_brand'),
     'item_category': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_category'),
     'item_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_id'),
     'item_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_id_raw'),
     'item_shop': TensorSpec(shape=(None, 1), dtype=tf.int32, name='item_shop'),
     'user_age': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_age'),
     'user_brands': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_brands'),
     'user_categories': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_categories'),
     'user_consumption_2': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_consumption_2'),
     'user_gender': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_gender'),
     'user_geography': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_geography'),
     'user_group': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_group'),
     'user_id': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_id'),
     'user_id_raw': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_id_raw'),
     'user_intentions': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_intentions'),
     'user_is_occupied': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_is_occupied'),
     'user_profile': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_profile'),
     'user_shops': TensorSpec(shape=(None, 1), dtype=tf.int32, name='user_shops')}
        * None
        * True
        * False
        * False
      Keyword arguments: {}
    
    Call arguments received by layer "model" "                 f"(type merlin.models>Model):
      • args=({'item_brand': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'item_category': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'item_id': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'item_id_raw': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'item_shop': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_age': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_brands': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_categories': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_consumption_2': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_gender': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_geography': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_group': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_id': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_id_raw': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_intentions': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_is_occupied': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_profile': 'tf.Tensor(shape=(None, 1), dtype=int32)', 'user_shops': 'tf.Tensor(shape=(None, 1), dtype=int32)'}, 'None', 'False', 'None', 'None')
      • kwargs=<class 'inspect._empty'>

```

### Steps/Code to reproduce bug

Please run the two notebooks in this [folder](https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/Building-and-deploying-multi-stage-RecSys) to repro the issue.

### Expected behavior

We should be able to export the configs without any errors.

### Environment details

- Merlin version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

I am using `merlin-tensorflow:22.12` and pulling all the latest branches from `main`.

### Additional context

If I use `merlin-tensorflow:22.12` image as it is (without pulling the latest main branches, the example nb works fine)

**Comment by rnyak** [comment]
@viswa-nvidia fyi.

**Comment by karlhigley** [comment]
This looks like some kind of pickling error related to trying to save out the model, which shouldn't be happening (but clearly is.)

**Comment by rnyak** [comment]
> This looks like some kind of pickling error related to trying to save out the model, which shouldn't be happening (but clearly is.)

thanks @karlhigley any easy fix I can do at my end?

**Comment by karlhigley** [comment]
@jperez999 I think the Triton operators should exclude their models and other artifacts from the state that gets pickled, [like we do for Dask clients in Merlin executors](https://github.com/NVIDIA-Merlin/core/blob/main/merlin/dag/executors.py#LL243-L245C73).
